---
- name: Restart node_exporter
  ansible.builtin.service:
    name: prometheus-node-exporter
    state: restarted
  listen: "restart node_exporter"

- name: Verify node_exporter is responding to requests
  ansible.builtin.uri:
    url: "http://{% if node_exporter_host != '' %}{{ node_exporter_host }}{% else %}localhost{% endif %}:{{ node_exporter_port }}/"
    return_content: true
  retries: 5
  delay: 3
  register: metrics_output
  failed_when: "'Metrics' not in metrics_output.content"
  listen: "restart node_exporter"
